### ISSUE TITLE
R&D Playing Game Logic & Scoring System

### ISSUE THREAD

**Issue by BrandonGranucci** [FragFault/FastThumbs#19]
This issue will require coming up with the best potential ways for functionality of the typing game. This involves the interaction between the given prompt and user input. Based off of whether the player is graded in real time or not, the appearance and functionality will alter.
- [x] Create theoretical solution(s). Involves giving reasoning and links to external resources.
- [x] Create skeleton code for given solution(s) if possible.

**Comment by ralcarmona** [comment]
https://stackoverflow.com/questions/25415166/android-check-an-edittext-input-box-each-type-the-user-types-in-a-character

**Comment by BrandonGranucci** [comment]
#  Game Logic Overview

Check if character entered is correct:
1. If correct: 
    1.  Increment var for num chars correct
    2. Highlight character green 
    3. Check if correct char is space and if so, acknowledge a word was completed
    4. Move to next character 
2. If incorrect: 
    1. Increment var for num chars wrong

# Accuracy & Speed Logic Overview
## Accuracy Logic:
1. Run formula (Located below)
2. (UNDER CONSIDERATION) -> Check if result is less than zero and if so, set to zero

## Speed Logic:
1. Increment WPM counter after each correct space is matched
2. Add one word to WPM counter if prompt succesfully completed.

# ALL SKELETON CODE BELOW

## For dynamically changing text color upon key strokes, use Span
<pre>
val spannable = SpannableStringBuilder("Text is spantastic!")
</pre>
## Have counters for current letter, num keystokes correct, num keystrokes incorrect, and wordsPerMinute:
<pre>
val currentLetter = 0
val charsCorrect = 0
val charsIncorrect = 0
val wordsPerMinute = 0
</pre>
## Update upon each correct key stroke:
<pre>
spannable.setSpan(
    ForegroundColorSpan(Color.GREEN),
    0,             // start
    currentLetter, // char the player is expected to type
    Spannable.SPAN_EXCLUSIVE_INCLUSIVE
)
</pre>
## When KeyListener reads input, process it:
<pre>
edittext.setOnKeyListener(new OnKeyListener() {
    @Override
    public boolean onKey(View v, int keyCode, KeyEvent event) {
        char pressedKey = (char) KeyEvent.getUnicodeChar();
        if (pressedkey != spannable[currentLetter]) {
            charIncorrect += 1
            return false;
        }
        else {
            if (pressedKey == " ") {
                wordsPerMinute += 1
            }
            charsCorrect += 1
            currentLetter += 1
            spannable.setSpan(
                ForegroundColorSpan(Color.GREEN),
                0,             // start
                currentLetter, // up to last correct char
                Spannable.SPAN_EXCLUSIVE_INCLUSIVE
            )
            return true;
        }
    }
});
</pre>
## Check if prompt is complete:
<pre>
if (charsCorrect == Spannable.length) {
    // TODO ->
    // 1) End Game (Move to results)
    // 2) Grade Score & Accuracy
    // 3) Save Results (To Backend)
}
</pre>
## Grade Accuracy:
<pre>
val accuracy = (charsCorrect-charsIncorrect)/charsCorrect
</pre>
(MAY OR MAY NOT BE NECESSARY CODE FOR CHECKING ACCURACY)
In case accuracy is less than 0:
<pre>
 if (accuracy < 0) {
      accuracy = 0
 }
</pre>

## Grade Speed:

### IN KEYLISTENER
<pre>
 else { // If keystroke matches expected:
     if (pressedKey == " ") {
         wordsPerMinute += 1
     } 
 }
</pre>
### IN CHECKING IF PROMPT IS COMPLETE
 wordPerMinute += 1

## Links Used:
1. https://stackoverflow.com/questions/13008752/onclicklistener-to-a-keyboard-button
2. https://developer.android.com/develop/ui/views/text-and-emoji/spans
