### ISSUE TITLE
Create API Wrapper

### ISSUE THREAD

**Issue by ralcarmona** [FragFault/FastThumbs#2]
- [ ] Create API wrapper which provides a midpoint between the app and the APIs.

**Comment by Dawidbtc** [comment]
The API Wrapper has been finished. It has been implemented in commit https://github.com/FragFault/FastThumbs/commit/2888c11b9eae432ecbc8c21c4c189ab8444d6e29

Deployed on AWS: 
Default State: http://52.87.203.225/ 
Get Movie Prompt: http://52.87.203.225/api/getMoviePrompt
Get Poetry Prompt: http://52.87.203.225/api/getPoetryPrompt
Get Lyrics Prompt: http://52.87.203.225/api/getLyricsPrompt
