### ISSUE TITLE
Login & Register Page Functionality

### ISSUE THREAD

**Issue by BrandonGranucci** [FragFault/FastThumbs#33]
For login page.
- [ ] User can enter login credentials and attempt login.
- [ ] User will be notified if login credentials are bad.
- [ ] User will be moved to level select page if login credentials are good.
- [ ] User's login info will be saved. (Create session)
- [ ] User can navigate to register screen.

For registration page.
- [ ] User can enter new account details and attempt registration.
- [ ] User will be notified if account information is bad.
- [ ] User will be moved to level select page if account information is good.
- [ ] User's login info will be saved. (Create session)
- [ ] User account will be created on the backend.
- [ ] User can navigate to login screen.

**Comment by mrpavsss** [comment]
completed in login branch
commits - [added sign up activity(full functionality and design), created applic…](https://github.com/FragFault/FastThumbs/commit/f4b107a7b87c4fe1eee5244e6103c79fabdc1b94) & [login branch initial](https://github.com/FragFault/FastThumbs/commit/1677c9a5f00c8bb5540e233e2195bff2d83e8a23)
